### PR TITLE
Add Flatpak to the download options for Linux

### PR DESCRIPTION
**Pull request by daenney**
I'm not very familiar with Vue, but I think this works?

### CODE REVIEW

**Comment by daenney** [comment]
@JannisX11 Mmm, the "downloads" page has gone missing on blockbench.net now. I don't believe that's caused by this PR, but probably the deployment of it?

**Comment by daenney** [comment]
Same for the plugins page

**Comment by JannisX11** [comment]
What error message are you receiving? The page works fine for me.

**Comment by daenney** [comment]
Sorry, my bad. I was blocking some XHR calls to third-party domains and it needed to reach out to GitHub to load some of the content.

**Pull request merged**
